version: '3.8'
services:
  mongodb:
    image: mongodb/mongodb-community-server
    ports:
      - '27017:27017'
    command: [--auth]
    environment:
      - MONGO_INITDB_ROOT_USERNAME=1207202
      - MONGO_INITDB_ROOT_PASSWORD=MHDAFR6BHCTYTE3A
    volumes:
      - dbdata6:/data/db
volumes:
  dbdata6:
