version: '3.8'
services:
  mongodb:
    image: mongodb/mongodb-community-server
    ports:
      - '27017:27017'
    volumes:
      - dbdata6:/data/db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=12072023
      - MONGO_INITDB_ROOT_PASSWORD=MHDAFR6BHCTYTE3A
volumes:
  dbdata6:
