version: "3.8"
services:
  mysql:
    image: mysql:latest
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: C$PBHyNx2X#tn&qF
    ports:
      - 3306:3306
    volumes:
      - mysql-data:/var/lib/mysql
volumes:
  mysql-data:
